# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainPage.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtWidgets import QAction
from PyQt5 import QtCore, QtGui, QtWidgets
from Data_Preprocessing import *
from SVD_Algo import *
import pandas as pd
import time
from Data_Preparation import *
from SVD import *
from NBC import *
from KNN import *
from AboutPage import AboutWindow

class Ui_MainWindow(object):
    
    def setupUi(self, MainWindow):
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1267, 665)
        MainWindow.setMouseTracking(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 0, 1031, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(360, 170, 101, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(360, 220, 211, 61))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.comboBox.setFont(font)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(780, 220, 171, 61))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.clicked.connect(self.on_pushButton_clicked)
        self.textBrowser = QtWidgets.QTextBrowser(self.centralwidget)
        self.textBrowser.setGeometry(QtCore.QRect(360, 320, 591, 261))
        self.textBrowser.setObjectName("textBrowser")
        MainWindow.setCentralWidget(self.centralwidget)
        
        
        
        
        
       
        self.actionDataset = QtWidgets.QAction(MainWindow)
        self.actionDataset.setObjectName("actionDataset")

        
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Recommendation System"))
        self.label.setText(_translate("MainWindow", "Product Recommendation System Based on Users with Similar Choices"))
        self.label_2.setText(_translate("MainWindow", "Algorithm"))
        self.comboBox.setItemText(0, _translate("MainWindow", "SVD"))
        self.comboBox.setItemText(1, _translate("MainWindow", "K-NN"))
        self.comboBox.setItemText(2, _translate("MainWindow", "Naive Bayesian Classifier"))
        self.pushButton.setText(_translate("MainWindow", "Apply"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:7.8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Results...</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        
    
    def on_pushButton_clicked(self):
        # Get the current value of the comboBox
        selected_algorithm = self.comboBox.currentText()

        # Clear the text browser
        self.textBrowser.clear()

        # Call the appropriate function based on the selected algorithm
        if selected_algorithm == "SVD":
            self.apply_svd_algorithm()
        elif selected_algorithm == "K-NN":
            self.apply_knn_algorithm()
        elif selected_algorithm == "Naive Bayesian Classifier":
            self.apply_naive_bayesian_algorithm()

    from PyQt5.QtCore import QCoreApplication

    def apply_svd_algorithm(self):
        # Your code for applying SVD algorithm goes here
        result_text = "SVD Algorithm Applied\n"
        # Append additional information or results to result_text if needed
        self.textBrowser.insertPlainText(result_text)
        # SVD Algorithm
        start_time = time.time()
        temp_head, num_recommendations = SVD_RS()
        self.textBrowser.insertPlainText(temp_head)
        print("SVD time : %s seconds" % (time.time() - start_time))

    def apply_knn_algorithm(self):
        # Your code for applying K-NN algorithm goes here
        result_text = "K-NN Algorithm Applied\n"
        # Append additional information or results to result_text if needed
        self.textBrowser.insertPlainText(result_text)

    def apply_naive_bayesian_algorithm(self):
        # Your code for applying Naive Bayesian Classifier algorithm goes here
        result_text = "Naive Bayesian Classifier Algorithm Applied\n"
        # Append additional information or results to result_text if needed
        self.textBrowser.insertPlainText(result_text)

    def on_about_clicked():
        msg = QMessageBox()
        msg.setIcon(QMessageBox.Information)
        msg.setWindowTitle("About")
        msg.setText("<h1>IMDB Recommender</h1>"
                    "<h3>Version 2.0</h3>"
                    "<b>Created by:</b> İbrahim Soner İNAN<br><br>"
                    "<a href='https://github.com/isonerinan'>GitHub</a><br><br>"
                    "<a href='https://www.linkedin.com/in/isonerinan'>LinkedIn</a><br><br>"
                    "<a href='https://www.instagram.com/isonerinan'>Instagram</a><br><br>"
                    "<a href='https://www.twitter.com/isonerinan'>Twitter</a>")
        msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
